# This is a basic workflow to help you get started with Actions

name: Build Jars and Commit

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 8
          distribution: adopt-openj9
          
      

          
      - name: Set up JDK 17
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 17
          distribution: adopt-openj9
          
      - name: Prepare PaperSpigot
        run: |
          mkdir PaperBuildTools
          cd PaperBuildTools
          git clone https://github.com/PaperMC/Paper
          git config --global user.email "paperbuild@fyrehost.net"
          git config --global user.name "Fyre Host"
          
      - name: Build 1.18.1 Paper Jar
        run: |
          cd PaperBuildTools
          cd Paper
          echo 'Building 1.18.1 Paper Jar'
          ./gradlew applyPatches
          ./gradlew createReobfBundlerJar
          cd build
          cd libs
          mv -f paper-bundler-1.18.1-R0.1-SNAPSHOT-reobf.jar ../../../../paper/1.18.1.jar
          cd ..
          cd ..
          git clean -fdX
          
      - name: Set up JDK 16
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 16
          distribution: adopt-openj9
          
      - name: Build 1.17.1 Paper Jar
        run: |
          cd PaperBuildTools
          cd Paper
          git checkout ver/1.17.1
          echo 'Building 1.17.1 Jar'
          ./gradlew applyPatches >> /dev/null 2>&1
          ./gradlew reobfJar >> /dev/null 2>&1
          cd Paper-Server/build/libs
          mv -f Paper-Server-1.17.1-R0.1-SNAPSHOT-mojang-mapped.jar ../../../../../paper/1.17.1.jar
          
      - name: Set up JDK 8
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 8
          distribution: adopt-openj9
          
      - name: Build rest of Paper Jars
        run: |
          cd PaperBuildTools
          cd Paper
          git restore .
          git clean -fdX
          git checkout ver/1.16.5
          git clean -fdX
          
          echo 'Making 1.16.5'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.16.5.jar
          git restore .
          git clean -fdX
          git checkout ver/1.15.2
          git clean -fdX
          
          echo 'Making 1.15.2'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.15.2.jar
          git restore .
          git clean -fdX
          git checkout ver/1.14
          git clean -fdX
          
          echo 'Making 1.14'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.14.jar
          git restore .
          git clean -fdX
          git checkout ver/1.13.2
          git clean -fdX
          
          echo 'Making 1.13.2'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.13.2.jar
          
          git restore .
          git clean -fdX
          git checkout ver/1.12.2
          git clean -fdX
          
          echo 'Making 1.12.2'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.12.2.jar
          
          git restore .
          git clean -fdX
          git checkout ver/1.11.2
          git clean -fdX
          
          echo 'Making 1.11.2'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.11.2.jar
          
          git restore .
          git clean -fdX
          git checkout ver/1.10.2
          git clean -fdX
          
          echo 'Making 1.10.2'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.10.2.jar
          
          git restore .
          git clean -fdX
          git checkout ver/1.9.4
          git clean -fdX
          
          echo 'Making 1.9.4'
          
          ./paper jar >> /dev/null 2>&1
          mv -f paperclip.jar ../../paper/1.9.4.jar
          
          git restore .
          git clean -fdX
          git checkout ver/1.12.2
          git clean -fdX
          
          echo 'Making 1.12.2'
          
          bash ./build.sh >> /dev/null 2>&1
          
          mv -f paperclip.jar ../../paper/1.8.8.jar'
          
      - name: Commit Changes
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'spigot'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: FyreHost Bot

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: git@fyrehost.net

      - name: Commit Changes Paper
        uses: EndBug/add-and-commit@v7 # You can change this to use a specific version.
        with:
          # The arguments for the `git add` command (see the paragraph below for more info)
          # Default: '.'
          add: 'paper'

          # The name of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_name: FyreHost Bot

          # The email of the user that will be displayed as the author of the commit.
          # Default: depends on the default_author input
          author_email: git@fyrehost.net
