name: 'Build Spigot Jars'

on:
    workflow_dispatch:

jobs:
    java17:
        strategy:
            matrix:
                version: [1.19.3, 1.19.2, 1.19.1, 1.19, 1.18.2, 1.18.1, 1.18]
        runs-on: ubuntu-latest
        steps:
          - name: Setup Java 17
            uses: actions/setup-java@v3.9.0
            with:
                java-version: 17
                distribution: adopt-openj9
                
          - name: Setup Buildtools
            run: |
              mkdir SpigotBuildTools
              cd SpigotBuildTools
              wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          
          - name: Build Jar
            run: |
              cd SpigotBuildTools
              java -jar BuildTools.jar --rev ${{ matrix.version }}
              mkdir ../build
              mv -f spigot-${{ matrix.version }}.jar ../build/
              
          - name: S3 File Upload
            uses: jakejarvis/s3-sync-action@v0.5.1
            env:
                AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                AWS_REGION: 'auto'
                AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                SOURCE_DIR: build
                DEST_DIR: spigot
                
    java16:
        strategy:
            matrix:
                version: [1.17.1, 1.17]
        runs-on: ubuntu-latest
        steps:
          - name: Setup Java 16
            uses: actions/setup-java@v3.9.0
            with:
                java-version: 16
                distribution: adopt-openj9
                
          - name: Setup Buildtools
            run: |
              mkdir SpigotBuildTools
              cd SpigotBuildTools
              wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          
          - name: Build Jar
            run: |
              cd SpigotBuildTools
              java -jar BuildTools.jar --rev ${{ matrix.version }}
              mkdir ../build
              mv -f spigot-${{ matrix.version }}.jar ../build/
              
          - name: S3 File Upload
            uses: jakejarvis/s3-sync-action@v0.5.1
            env:
                AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                AWS_REGION: 'auto'
                AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                SOURCE_DIR: build
                DEST_DIR: spigot
                
    java8:
        strategy:
            matrix:
                version: [1.16.5, 1.16.4, 1.16.3, 1.16.2, 1.16.1, 1.15.2, 1.15.1, 1.15, 1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14, 1.13.2, 1.13.1, 1.13, 1.12.2, 1.12.1, 1.12, 1.11.2, 1.11, 1.10.2, 1.9.4, 1.9.2, 1.9, 1.8.8, 1.8.3, 1.8]
        runs-on: ubuntu-latest
        steps:
          - name: Setup Java 8
            uses: actions/setup-java@v3.9.0
            with:
                java-version: 8
                distribution: adopt-openj9
                
          - name: Setup Buildtools
            run: |
              mkdir SpigotBuildTools
              cd SpigotBuildTools
              wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
          
          - name: Build Jar
            run: |
              cd SpigotBuildTools
              java -jar BuildTools.jar --rev ${{ matrix.version }}
              mkdir ../build
              mv -f spigot-${{ matrix.version }}.jar ../build/
              
          - name: S3 File Upload
            uses: jakejarvis/s3-sync-action@v0.5.1
            env:
                AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
                AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                AWS_REGION: 'auto'
                AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
                SOURCE_DIR: build
                DEST_DIR: spigot
